[package]
name = "IBF-hq-client"
version = "1.2.3"
edition = "2024"
description = "Ore mining pool client. Credit to Ecl1pse Mining Pool"
license = "Apache-2.0"
repository = ""
keywords = ["solana", "crypto", "mining", "client", "mining-pool"]

[dependencies]
base64 = "0.22.1"
bincode = "1.3.3"
clap = { version = "4.5.13", features = ["derive"] }
core_affinity = "0.8.1"
ore-api = "2.1.0"
ore-utils = "2.1.0"
drillx = "2.0.0"
#drillx = { path = "../../regolith-labs/forks/drillx/drillx" }
futures-util = "0.3.30"
reqwest = "^0.11.0"
rpassword = "7.3.1"
solana-sdk = "1.18.12"
tokio = { version = "1.39.2", features = ["full"] }
tokio-tungstenite = { version = "0.23.1", features = ["native-tls"] }
url = "2.5.2"
spl-token = "6.0.0"
